# Generated by Django 4.0.3 on 2022-03-14 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
