# Generated by Django 4.0.3 on 2022-03-10 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product',
            new_name='movie',
        ),
    ]
