# Generated by Django 4.0.3 on 2022-03-11 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
