# Generated by Django 4.0.3 on 2022-03-12 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
