# Generated by Django 4.0.3 on 2022-03-13 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
