# Generated by Django 4.0.3 on 2022-03-28 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0011_review_frames'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='frames',
            new_name='frame',
        ),
    ]
