# Generated by Django 4.0.3 on 2022-03-28 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0012_rename_frames_review_frame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='frame',
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.ImageField(upload_to='review_frames')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame', to='review.review')),
            ],
        ),
    ]
